### ISSUE TITLE
请教一个问题，部署成功了，通信也正常，但是点开具体设备的详情页提示数据加载失败

### ISSUE THREAD

**Issue by shaneZhang** [cnly1987/nq-server-simple#1]
部署成功了，通信也正常，查看了一下mongodb里的表也有数据，records表，点开具体设备的详情页提示数据加载失败，请教下是什么问题？

**Comment by shaneZhang** [comment]
查看了一下是http://nodequery.n1.box/api/records/14/    500错误

**Comment by shaneZhang** [comment]
MongoError: Unrecognized expression '$toDate'
    at MessageStream.messageHandler (/home/nq-server-simple/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (node:events:378:20)
    at processIncomingData (/home/nq-server-simple/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/nq-server-simple/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:400:12)
    at _write (node:internal/streams/writable:341:10)
    at MessageStream.Writable.write (node:internal/streams/writable:345:10)
    at Socket.ondata (node:internal/streams/readable:750:22)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)

**Comment by cnly1987** [comment]
> MongoError: Unrecognized expression '$toDate'
> at MessageStream.messageHandler (/home/nq-server-simple/node_modules/mongodb/lib/cmap/connection.js:268:20)
> at MessageStream.emit (node:events:378:20)
> at processIncomingData (/home/nq-server-simple/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
> at MessageStream._write (/home/nq-server-simple/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
> at writeOrBuffer (node:internal/streams/writable:400:12)
> at _write (node:internal/streams/writable:341:10)
> at MessageStream.Writable.write (node:internal/streams/writable:345:10)
> at Socket.ondata (node:internal/streams/readable:750:22)
> at Socket.emit (node:events:378:20)
> at addChunk (node:internal/streams/readable:313:12)

$toDate方法是mongodb 4.0以上才有的， 显然这个报错是说$toDate方法不存在，所以是你的mongodb版本太低。
建议是安装mongodb4.2，如果不会，请查看http://www.awkxy.com/Linux/mongodb.html

**Comment by shaneZhang** [comment]
感谢老吴指点，果然是升级一下MongoDB就没问题了，可以在文档中写一下，MongoDB最低支持的版本.多谢。
